from datetime import date, timedelta

from .records import insert_record
from .utils import today_str


def seed_sample_data(db) -> None:
    row = db.fetchone("SELECT COUNT(*) as total FROM records")
    if row and row["total"] > 0:
        return

    base = date.today()
    samples = [
        {
            "category": "Protocolos Judiciais",
            "doc_number": "PJ-2026-001",
            "record_date": (base - timedelta(days=10)).strftime("%Y-%m-%d"),
            "interested": "Servidor A",
            "origin": "Vara Civel",
            "subject": "Analise de processo",
            "status": "Em andamento",
            "tags": "prazo, urgente",
            "notes": "Prazo curto para resposta.",
            "process_number": "0001234-56.2026.8.01.0001",
            "court": "1a Vara",
            "deadline_date": (base + timedelta(days=3)).strftime("%Y-%m-%d"),
            "deadline_status": "Alerta",
        },
        {
            "category": "Informacoes",
            "doc_number": "INF-2026-002",
            "record_date": (base - timedelta(days=9)).strftime("%Y-%m-%d"),
            "interested": "Servidor B",
            "origin": "Setor X",
            "subject": "Solicitacao de informacoes",
            "status": "Aberto",
            "tags": "retorno",
            "notes": "Aguardando resposta.",
            "recipient": "Setor Y",
            "send_method": "E-mail",
        },
        {
            "category": "Oficios",
            "doc_number": "OF-2026-003",
            "record_date": (base - timedelta(days=8)).strftime("%Y-%m-%d"),
            "interested": "Servidor C",
            "origin": "Gabinete",
            "subject": "Oficio de encaminhamento",
            "status": "Concluido",
            "tags": "encaminhado",
            "recipient": "Secretaria",
            "send_method": "SEI",
            "send_date": (base - timedelta(days=7)).strftime("%Y-%m-%d"),
        },
        {
            "category": "Convocacoes",
            "doc_number": "CONV-2026-004",
            "record_date": (base - timedelta(days=7)).strftime("%Y-%m-%d"),
            "interested": "Servidor D",
            "origin": "RH",
            "subject": "Convocacao para reuniao",
            "status": "Concluido",
            "tags": "reuniao",
            "convocation_date": (base - timedelta(days=5)).strftime("%Y-%m-%d"),
            "convocation_location": "Sala 2",
            "convoked_person": "Pessoa X",
            "attended": 1,
        },
        {
            "category": "Agendamentos",
            "doc_number": "AG-2026-005",
            "record_date": (base - timedelta(days=6)).strftime("%Y-%m-%d"),
            "interested": "Servidor E",
            "origin": "Saude",
            "subject": "Agendamento medico",
            "status": "Em andamento",
            "tags": "saude",
            "schedule_datetime": (base + timedelta(days=2)).strftime("%Y-%m-%d 10:00"),
            "schedule_type": "Medico",
            "schedule_location": "Clinica A",
            "schedule_confirmed": 1,
        },
        {
            "category": "Despachos",
            "doc_number": "DES-2026-006",
            "record_date": (base - timedelta(days=5)).strftime("%Y-%m-%d"),
            "interested": "Servidor F",
            "origin": "Diretoria",
            "subject": "Despacho interno",
            "status": "Arquivado",
            "tags": "interno",
            "recipient": "Equipe Z",
            "send_method": "Outro",
        },
        {
            "category": "Memorandos",
            "doc_number": "MEM-2026-007",
            "record_date": (base - timedelta(days=4)).strftime("%Y-%m-%d"),
            "interested": "Servidor G",
            "origin": "Setor Financeiro",
            "subject": "Memorando de pagamento",
            "status": "Concluido",
            "tags": "financeiro",
            "recipient": "Contabilidade",
            "send_method": "E-mail",
        },
        {
            "category": "Projetos",
            "doc_number": "PROJ-2026-008",
            "record_date": (base - timedelta(days=3)).strftime("%Y-%m-%d"),
            "interested": "Servidor H",
            "origin": "Projetos",
            "subject": "Implantacao sistema",
            "status": "Em andamento",
            "tags": "projeto",
            "project_stage": "Planejamento",
            "project_responsible": "Equipe TI",
            "project_due_date": (base + timedelta(days=30)).strftime("%Y-%m-%d"),
            "project_status": "Ativo",
        },
        {
            "category": "Outros",
            "doc_number": "OUT-2026-009",
            "record_date": (base - timedelta(days=2)).strftime("%Y-%m-%d"),
            "interested": "Servidor I",
            "origin": "Setor Geral",
            "subject": "Registro diverso",
            "status": "Aberto",
            "tags": "diverso",
        },
        {
            "category": "Protocolos Judiciais",
            "doc_number": "PJ-2026-010",
            "record_date": today_str(),
            "interested": "Servidor J",
            "origin": "Comarca",
            "subject": "Reiteracao de protocolo",
            "status": "Aberto",
            "tags": "retorno",
            "process_number": "0009999-11.2026.8.01.0002",
            "court": "2a Vara",
        },
    ]

    for record in samples:
        insert_record(db, record)
